import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Navbar} from "@/app/components/navbar/Navbar";
import {InnerLayout} from "@/app/components/InnerLayout";
import 'tippy.js/dist/tippy.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden h-[100dvh] w-[100dvw]`}>
          <InnerLayout>
              <Navbar />
              {children}
          </InnerLayout>
      </body>
    </html>
  );
}
